### PR TITLE
fix offering and add protocol field

### LINKED ISSUE #54: Add `protocol` to `Resource`, `ResourceMetadata`
Add `protocol` field to `Resource`, `ResourceMetadata`

[tbdex-js implementation](https://github.com/TBD54566975/tbdex-js/blob/46481e7fe74111f4f8a3cc7bf3f7943843a30cf7/packages/protocol/src/types.ts#L34-L35)

### LINKED ISSUE #55: Remove `fee` from `PaymentMethod` in `OfferingData`
`fee` should be removed from `PaymentMethod` in `OfferingData`

[tbdex-js implementation](https://github.com/TBD54566975/tbdex-js/blob/46481e7fe74111f4f8a3cc7bf3f7943843a30cf7/packages/protocol/src/types.ts#L96-L101)

### LINKED ISSUE #57: [Bug] `getOfferings()` erroring because of Date properties
When calling `getOfferings` against the [tbdex pfi exempler](https://github.com/TBD54566975/tbdex-pfi-exemplar) (as well as any other PFI), an error occurs:

> Failed to fetch offerings: Error(reason: "Error while fetching offerings: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: \"data\", intValue: nil), _JSONKey(stringValue: \"Index 0\", intValue: 0), CodingKeys(stringValue: \"metadata\", intValue: nil), CodingKeys(stringValue: \"createdAt\", intValue: nil)], debugDescription: \"Expected to decode String but found number instead.\", underlyingError: nil))")

Found by @blackgirlbytes 🙌🏾

### PR DESCRIPTION
**Pull request by kirahsapong**
Also removes `fee` from `OfferingData`

closes #55 
closes #54 
closes #57

### CODE REVIEW

File: Tests/tbDEXTests/Protocol/Models/Resources/OfferingTests.swift [hunk 1]
```diff
@@ -4,49 +4,35 @@ import XCTest
...
...e of the card in MM/YY format\",\"pattern\":\"^(0[1-9]|1[0-2])\\\\/([0-9]{2})$\"},\"cardHolderName\":{\"type\":\"string\",\"description\":\"Name of the cardholder as it appears on the card\"},\"cvv\":{\"type\":\"string\",\"description\":\"The 3-digit CVV code\",\"minLength\":3,\"maxLength\":3}},\"required\":[\"cardNumber\",\"expiryDate\",\"cardHolderName\",\"cvv\"],\"additionalProperties\":false}}],\"payoutMethods\":[{\"kind\":\"BTC_ADDRESS\",\"requiredPaymentDetails\":{\"$schema\":\"http://json-schema.org/draft-07/schema\",\"type\":\"object\",\"properties\":{\"btcAddress\":{\"type\":\"string\",\"description\":\"your Bitcoin wallet address\"}},\"required\":[\"btcAddress\"],\"additionalProperties\":false}}],\"requiredClaims\":{\"id\":\"7ce4004c-3c38-4853-968b-e411bafcd945\",\"input_descriptors\":[{\"id\":\"bbdb9b7c-5754-4f46-b63b-590bada959e0\",\"constraints\":{\"fields\":[{\"path\":[\"$.type\"],\"filter\":{\"type\":\"string\",\"const\":\"YoloCredential\"}}]}}]}},\"signature\":\"eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDpkaHQ6NzdlbTFmOTY4YzFnendycmIxNWNna3pqeGc4cmZ0NjdlYnhqNmdqa29jbno1cDhzZG5peSMwIn0..puQwdTvi4KTfKedA6CXdHHldztoQ8udUrQrGmw1wvWfYW3ilMB8myoD3ATw7NGlt1NuizJ80i4ufZArgGrTiAA\"}"
```
Comment (nitro-neal) [inline Tests/tbDEXTests/Protocol/Models/Resources/OfferingTests.swift:30]: chad says:

let offeringJson = """
{
    "metadata": {
        "from": "did:dht:77em1f968c1gzwrrb15cgkzjxg8rft67ebxj6gjkocnz5p8sdniy",
        "protocol": "1.0",
        "kind": "offering",
        "id": "offering_01hrqn6ph3f00asxqvx46capbw",
        "createdAt": "2024-03-11T21:02:55.523Z"
    },
    "data": {
        "description": "Selling BTC for USD",
        "payinCurrency": {
            "currencyCode": "USD",
            "minAmount": "0.0",
            "maxAmount": "999999.99"
        },
        "payoutCurrency": {
            "currencyCode": "BTC",
            "maxAmount": "999526.11"
        },
        "payoutUnitsPerPayinUnit": "0.00003826",
        "payinMethods": [
            {
                "kind": "DEBIT_CARD",
                "requiredPaymentDetails": {
                    "$schema": "http://json-schema.org/draft-07/schema",
                    "type": "object",
                    "properties": {
                        "cardNumber": {
                            "type": "string",
                            "description": "The 16-digit debit card number",
                            "minLength": 16,
                            "maxLength": 16
                        },
                        "expiryDate": {
                            "type": "string",
                            "description": "The expiry date of the card in MM/YY format",
                            "pattern": "^(0[1-9]|1[0-2])\\/([0-9]{2})$"
                        },
                        "cardHolderName": {
                            "type": "string",
                            "description": "Name of the cardholder as it appears on the card"
                        },
                        "cvv": {
                            "type": "string",
                            "description": "The 3-digit CVV code",
                            "minLength": 3,
                            "maxLength": 3
                        }
                    },
                    "required": [
                        "cardNumber",
                        "expiryDate",
                        "cardHolderName",
                        "cvv"
                    ],
                    "additionalProperties": false
                }
            }
        ],
        "payoutMethods": [
            {
                "kind": "BTC_ADDRESS",
                "requiredPaymentDetails": {
                    "$schema": "http://json-schema.org/draft-07/schema",
                    "type": "object",
                    "properties": {
                        "btcAddress": {
                            "type": "string",
                            "description": "your Bitcoin wallet address"
                        }
                    },
                    "required": [
                        "btcAddress"
                    ],
                    "additionalProperties": false
                }
            }
        ],
        "requiredClaims": {
            "id": "7ce4004c-3c38-4853-968b-e411bafcd945",
            "input_descriptors": [
                {
                    "id": "bbdb9b7c-5754-4f46-b63b-590bada959e0",
                    "constraints": {
                        "fields": [
                            {
                                "path": [
                                    "$.type"
                                ],
                                "filter": {
                                    "type": "string",
                                    "const": "YoloCredential"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "signature": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDpkaHQ6NzdlbTFmOTY4YzFnendycmIxNWNna3pqeGc4cmZ0NjdlYnhqNmdqa29jbno1cDhzZG5peSMwIn0..puQwdTvi4KTfKedA6CXdHHldztoQ8udUrQrGmw1wvWfYW3ilMB8myoD3ATw7NGlt1NuizJ80i4ufZArgGrTiAA"
}
"""

take it or leave it lol

**Review by nitro-neal — APPROVED** [review]

**Review by jiyoontbd — APPROVED** [review]
🌟
